%% Build config table
T = buildLinescanConfig();

%% Run Linescans
for iFile = 1:1:1 %size(T,1)
    try
        Result = linescan.linescanVelFromTiff(fullfile(T.Folder{iFile}, T.File{iFile}),...
                                     T.WinSize(iFile), T.WinStep(iFile),...
                                     'msPerLine', T.msPerLine{iFile},...
                                     'umPerPx', T.umPerPx{iFile},...
                                     'Mask', [T.MaskLeft(iFile),T.MaskRight(iFile)],...
                                     'Method', T.Method{iFile},...
                                     'Maxlines', T.Maxlines(iFile),...
                                     'UseAvg', T.UseAvg(iFile));
    catch ME
        disp(getReport(ME))
    end
end